name: Build on Dependabot PR

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  build:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    concurrency:
      group: dependabot-build
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: