name: Build on PR

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  build:
    if: |
      github.actor == 'dependabot[bot]' ||
      (github.event.pull_request.author_association == 'OWNER' ||
       github.event.pull_request.author_association == 'COLLABORATOR' ||
       github.event.pull_request.author_association == 'MEMBER')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run build command
        run: pnpm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist/

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const output = `✅ Build completed successfully!\n\nYou can view the build artifacts [here](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}).`;
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              });
            } catch (error) {
              const output = `❌ Build failed!\n\nCheck the [workflow logs](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.`;
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              });
              throw error; // Fail the job
            }
